spring:
  application:
    name: it-components-ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/it_components_ecommerce?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true

    # Driver cho MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Tài khoản MySQL cục bộ
    username: root
    password: 123456

  jpa:
    hibernate:
      # 'update' giúp tự động tạo bảng dựa trên Entity mà không xóa dữ liệu cũ
      ddl-auto: update
    show-sql: true # Hiện câu lệnh SQL ở console để dễ debug